services:
  rocketbot-challenge-api:
    container_name: rocketbot-challenge-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: unless-stopped
    networks:
      - rocketbot-network
    environment:
      - PYTHONPATH=/app

networks:
  rocketbot-network:
    driver: bridge
